permalink: /articles/:title/
title: I'M WOOZY
url: https://woozy.im
exclude: [README.md, CNAME]
domain: woozy.im
author: Zhenye Wei
email: weizhenye@gmail.com
excerpt_separator: <!-- more -->
googleAnalyticsID: UA-34447075-1
disqusShortName: muou