markdown: rdiscount
permalink: /:title
title: I'M WOOZY
url: http://woozy.im/
exclude: README.md
domain: woozy.im
author: weizhenye
email: weizhenye@gmail.com
auto: true
googleAnalyticsID: UA-34447075-1
disqusShortname: muou