markdown: rdiscount
permalink: /articles/:title
title: I'M WOOZY
url: http://woozy.im/
exclude: [README.md, CNAME]
domain: woozy.im
author: weizhenye
email: weizhenye@gmail.com
googleAnalyticsID: UA-34447075-1
disqusShortName: muou